# Generated by Django 5.2 on 2025-06-16 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("tournoi", "Tournoi"),
                            ("competition", "Compétition"),
                            ("stream", "Stream"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateTimeField()),
                ("date_fin", models.DateTimeField()),
                ("jeu", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("lieu", models.CharField(max_length=200)),
                ("lien_inscription", models.URLField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="evenements/images/"
                    ),
                ),
                ("places_disponibles", models.IntegerField(default=0)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("est_actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["date_debut"],
            },
        ),
        migrations.CreateModel(
            name="InscriptionEvenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                ("est_confirmee", models.BooleanField(default=False)),
                ("commentaire", models.TextField(blank=True)),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="evenements.evenement",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions_evenements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription à un événement",
                "verbose_name_plural": "Inscriptions aux événements",
                "ordering": ["-date_inscription"],
                "unique_together": {("evenement", "utilisateur")},
            },
        ),
    ]
