# Generated by Django 5.2 on 2025-05-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(verbose_name='URL YouTube')),
                ('actif', models.BooleanField(default=True, verbose_name='Streaming actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streamings', to='core.match')),
            ],
            options={
                'verbose_name': 'Streaming',
                'verbose_name_plural': 'Streamings',
                'ordering': ['-created_at'],
            },
        ),
    ]
