# Generated by Django 5.2 on 2025-06-16 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gameur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pseudo", models.CharField(max_length=50, unique=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="gameurs/avatars/"
                    ),
                ),
                ("jeu_prefere", models.CharField(max_length=100)),
                ("nombre_victoires", models.IntegerField(default=0)),
                ("nombre_defaites", models.IntegerField(default=0)),
                ("ratio", models.FloatField(default=0.0)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-ratio"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_match", models.DateTimeField(default=django.utils.timezone.now)),
                ("score_gameur1", models.IntegerField(default=0)),
                ("score_gameur2", models.IntegerField(default=0)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "gameur1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_joueur1",
                        to="gameurs.gameur",
                    ),
                ),
                (
                    "gameur2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_joueur2",
                        to="gameurs.gameur",
                    ),
                ),
                (
                    "vainqueur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_gagnes",
                        to="gameurs.gameur",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_match"],
            },
        ),
    ]
