# Generated by Django 5.0.1 on 2025-09-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="p2pchallenge",
            name="creator_bet_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Mise du créateur"
            ),
        ),
        migrations.AlterField(
            model_name="p2pchallenge",
            name="opponent_bet_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Mise de l'adversaire"
            ),
        ),
    ]
