# Generated by Django 5.0.1 on 2025-09-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0002_alter_p2pchallenge_creator_bet_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="p2pchallenge",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("dota2", "DOTA 2"),
                    ("tekken8", "TEKKEN 8"),
                    ("mlbb", "Mobile Legends: Bang Bang (MLBB)"),
                    ("pubg", "PUBG"),
                    ("csgo2", "Counter-Strike 2 (CS2)"),
                    ("efootball", "eFootball"),
                    ("fifa", "EA Sports FC (ex-FIFA)"),
                    ("lol", "League of Legends (LoL)"),
                    ("valorant", "Valorant"),
                    ("rocket_league", "Rocket League"),
                    ("other", "Autre"),
                ],
                max_length=20,
                verbose_name="Type de jeu",
            ),
        ),
    ]
