# Generated by Django 5.2 on 2025-05-18 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_add_game_id_to_bettype'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBet',
            fields=[
                ('bet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='betting.bet')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('match_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='Temps de jeu')),
                ('current_score', models.CharField(blank=True, max_length=20, null=True, verbose_name='Score actuel')),
            ],
            options={
                'verbose_name': 'Pari en direct',
                'verbose_name_plural': 'Paris en direct',
            },
            bases=('betting.bet',),
        ),
        migrations.AlterField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='core.match', verbose_name='Match'),
        ),
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pari', 'verbose_name_plural': 'Paris'},
        ),
        migrations.AlterModelOptions(
            name='bettype',
            options={'verbose_name': 'Type de pari', 'verbose_name_plural': 'Types de paris'},
        ),
        migrations.RemoveField(
            model_name='bet',
            name='potential_winnings',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='bettype',
            name='game',
        ),
        migrations.AddField(
            model_name='bet',
            name='choice',
            field=models.CharField(choices=[('team1', 'Équipe 1'), ('team2', 'Équipe 2'), ('draw', 'Match nul'), ('other', 'Autre')], default='team1', max_length=20, verbose_name='Choix'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='betting.bettype', verbose_name='Type de pari'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('won', 'Gagné'), ('lost', 'Perdu'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='bettype',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_types', to='core.game', verbose_name='Jeu'),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
