# Generated by Django 5.2.6 on 2025-09-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_alter_p2pchallenge_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2pchallenge',
            name='game_type',
            field=models.CharField(choices=[('fifa', 'FIFA'), ('pes', 'PES'), ('csgo', 'CS:GO'), ('lol', 'League of Legends'), ('valorant', 'Valorant'), ('rocket_league', 'Rocket League'), ('other', 'Autre')], max_length=20, verbose_name='Type de jeu'),
        ),
    ]
