# Generated by Django 5.2 on 2025-05-20 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0005_alter_bettype_game_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Montant",
            ),
        ),
    ]
