# Generated by Django 5.2 on 2025-05-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0006_alter_bet_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="choice",
            field=models.CharField(
                choices=[
                    ("team1", "Équipe 1"),
                    ("team2", "Équipe 2"),
                    ("draw", "Match nul"),
                    ("other", "Autre"),
                ],
                default="team1",
                max_length=50,
                verbose_name="Choix",
            ),
        ),
    ]
