# Generated by Django 5.2 on 2025-07-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0007_alter_bet_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="use_ktap",
            field=models.BooleanField(
                default=False, verbose_name="Parier avec mes KTAP (VIP)"
            ),
        ),
    ]
