# Generated by Django 5.2 on 2025-05-05 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du jeu')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='games/', verbose_name='Image du jeu')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('developer', models.CharField(blank=True, max_length=100, verbose_name='Développeur')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Jeu',
                'verbose_name_plural': 'Jeux',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'équipe")),
                ('logo', models.ImageField(upload_to='teams/', verbose_name='Logo')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Pays')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.game', verbose_name='Jeu')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du tournoi')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('organizer', models.CharField(max_length=100, verbose_name='Organisateur')),
                ('prize_pool', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prize pool')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tournaments/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='core.game', verbose_name='Jeu')),
            ],
            options={
                'verbose_name': 'Tournoi',
                'verbose_name_plural': 'Tournois',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Heure de début')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('status', models.CharField(choices=[('upcoming', 'À venir'), ('live', 'En cours'), ('completed', 'Terminé'), ('canceled', 'Annulé')], default='upcoming', max_length=10, verbose_name='Statut')),
                ('score_team1', models.IntegerField(blank=True, null=True, verbose_name='Score équipe 1')),
                ('score_team2', models.IntegerField(blank=True, null=True, verbose_name='Score équipe 2')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team', verbose_name='Équipe 1')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team', verbose_name='Équipe 2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team', verbose_name='Vainqueur')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.tournament', verbose_name='Tournoi')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['start_time'],
            },
        ),
    ]
