# Generated by Django 5.2 on 2025-05-20 12:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_create_deposit_request_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="ID de transaction",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=True,
                verbose_name="Identifiant unique",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Dépôt"),
                    ("withdrawal", "Retrait"),
                    ("win", "Gain"),
                    ("loss", "Perte"),
                    ("bonus", "Bonus"),
                    ("kapanga_purchase", "Achat de Kapanga"),
                    ("kapanga_usage", "Utilisation de Kapanga"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "transaction_type"],
                name="users_trans_user_id_57723f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["status", "timestamp"], name="users_trans_status_8c8e2b_idx"
            ),
        ),
    ]
