# Generated by Django 5.2 on 2025-05-20 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_transaction_options_transaction_transaction_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="Identifiant unique",
            ),
        ),
    ]
