# Generated by Django 5.2 on 2025-05-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_withdrawalrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="withdrawalrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Demande de retrait",
                "verbose_name_plural": "Demandes de retrait",
            },
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="Notes administrateur"),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom de la banque"
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="bic",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="BIC/SWIFT"
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="crypto_network",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ethereum", "Ethereum (ERC20)"),
                    ("bitcoin", "Bitcoin"),
                    ("tron", "TRON (TRC20)"),
                ],
                max_length=20,
                null=True,
                verbose_name="Réseau",
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="crypto_wallet",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Adresse du portefeuille",
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="iban",
            field=models.CharField(
                blank=True, max_length=34, null=True, verbose_name="IBAN"
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bank", "Virement Bancaire"),
                    ("paypal", "PayPal"),
                    ("crypto", "Cryptomonnaie"),
                ],
                max_length=20,
                null=True,
                verbose_name="Méthode de paiement",
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="paypal_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email PayPal"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Montant"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvée"),
                    ("rejected", "Rejetée"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de mise à jour"
            ),
        ),
    ]
