# Generated by Django 5.2 on 2025-05-22 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_withdrawalrequest_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="crypto_network",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="crypto_wallet",
        ),
        migrations.AlterField(
            model_name="user",
            name="kapanga_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Solde ktap",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("bank", "Virement Bancaire"), ("paypal", "PayPal")],
                max_length=20,
                null=True,
                verbose_name="Méthode de paiement",
            ),
        ),
    ]
