# Generated by Django 5.2 on 2025-05-22 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_withdrawalrequest_crypto_network_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameOrganizationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_name",
                    models.CharField(max_length=200, verbose_name="Nom du jeu proposé"),
                ),
                ("description", models.TextField(verbose_name="Détails de la demande")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvée"),
                            ("rejected", "Rejetée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notes administrateur"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_organization_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'organisation de jeu",
                "verbose_name_plural": "Demandes d'organisation de jeu",
                "ordering": ["-created_at"],
            },
        ),
    ]
