# Generated by Django 5.2 on 2025-05-24 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_add_reference_paiement_to_withdrawalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="crypto_address",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Adresse du portefeuille crypto",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Dépôt"),
                    ("withdrawal", "Retrait"),
                    ("win", "Gain"),
                    ("loss", "Perte"),
                    ("bonus", "Bonus"),
                    ("kapanga_purchase", "Achat de Ktap"),
                    ("kapanga_usage", "Utilisation de Ktap"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="kapanga_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Solde Ktap",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("crypto", "Crypto Money"), ("paypal", "PayPal")],
                max_length=20,
                null=True,
                verbose_name="Méthode de paiement",
            ),
        ),
    ]
