# Generated by Django 5.2 on 2025-05-28 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_promocode_promocodeusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bonus_conditions_met",
            field=models.BooleanField(
                default=False, verbose_name="Conditions de bonus remplies"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bonus_wagered_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Montant misé pour le bonus",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Solde bonus",
            ),
        ),
    ]
