# Generated by Django 5.2 on 2025-07-07 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_bonus_conditions_met_user_bonus_wagered_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VipEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("tournoi", "Tournoi"),
                            ("promotion", "Promotion"),
                            ("bonus", "Bonus"),
                            ("sport_event", "Événement sportif"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("vip_only", "VIP uniquement"),
                            ("public", "Public"),
                            ("invite_only", "Sur invitation"),
                        ],
                        default="public",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_vip",
            field=models.BooleanField(default=False, verbose_name="Statut VIP"),
        ),
        migrations.AddField(
            model_name="user",
            name="parrain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="filleuls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Parrain",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_bonus",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Total des bonus VIP",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="vip_points",
            field=models.IntegerField(default=0, verbose_name="Points VIP"),
        ),
        migrations.AddField(
            model_name="user",
            name="vip_since",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'activation VIP"
            ),
        ),
        migrations.CreateModel(
            name="FidelityPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("achat", "Achat"),
                            ("pari", "Pari"),
                            ("vente", "Vente"),
                            ("promotion", "Promotion"),
                        ],
                        max_length=15,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fidelity_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KtapToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("gain", "Gain"),
                            ("achat", "Achat"),
                            ("vente", "Vente"),
                            ("bonus", "Bonus"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("en_vente", "En vente"),
                            ("vendu", "Vendu"),
                        ],
                        default="disponible",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ktap_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VipBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_type",
                    models.CharField(
                        choices=[
                            ("journalier", "Journalier"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("evenementiel", "Événementiel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vip_bonuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VipSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "price_per_token",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("vendu", "Vendu"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vip_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
