# Generated by Django 5.2 on 2025-07-07 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_vipevent_user_is_vip_user_parrain_user_total_bonus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VIPRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("acceptee", "Acceptée"),
                            ("rejetee", "Rejetée"),
                        ],
                        default="en_attente",
                        max_length=10,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("commentaire_admin", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vip_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande VIP",
                "verbose_name_plural": "Demandes VIP",
                "ordering": ["-date"],
            },
        ),
    ]
