# Generated by Django 5.2 on 2025-06-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partenaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("logo", models.ImageField(upload_to="partenaires/logos/")),
                ("site_web", models.URLField()),
                (
                    "type_partenaire",
                    models.CharField(
                        choices=[
                            ("sponsor", "Sponsor"),
                            ("media", "Média"),
                            ("equipementier", "Équipementier"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                ("est_actif", models.BooleanField(default=True)),
                ("ordre_affichage", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
                "ordering": ["ordre_affichage", "nom"],
            },
        ),
    ]
