# Generated by Django 5.0.1 on 2025-09-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("slug", models.SlugField(unique=True)),
                ("ordre", models.IntegerField(default=0)),
                ("est_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("est_modifie", models.BooleanField(default=False)),
                ("est_resolu", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Sujet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("est_epingle", models.BooleanField(default=False)),
                ("est_verrouille", models.BooleanField(default=False)),
                ("nombre_vues", models.IntegerField(default=0)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Sujet",
                "verbose_name_plural": "Sujets",
                "ordering": ["-est_epingle", "-date_creation"],
            },
        ),
    ]
