# Generated by Django 5.0.1 on 2025-09-12 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="auteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sujet",
            name="auteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sujets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sujet",
            name="categorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sujets",
                to="forum.categorie",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sujet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="forum.sujet",
            ),
        ),
    ]
